version: '2.2'

services:
  app:
    build: .
    container_name: check_weather_ctn
    command:  python manage.py runserver 0.0.0.0:4000
#    command:  gunicorn check_weather.wsgi:application --bind 0.0.0.0:4000
    volumes:
    - ./app/:/opt/django/app/
    ports:
      - 4000:4000
    env_file:
      - ./.env.dev
    depends_on:
      - database
  database:
    image: postgres:12.0-alpine
    container_name: check_weather_db
    ports:
     - 2000:5432
    volumes:
      - postgres_data_db:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

volumes:
  postgres_data_db: